name: Build Lib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Lên đời hẳn macOS 14 (M2 Runner) cho máu, bỏ macos-13 khan hiếm máy ảo
    runs-on: macos-14

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 1. Kéo framework Theos về thủ công bằng git, không dùng script cài đặt tự động
    - name: Setup Theos Framework
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos

    # 2. Tự kéo SDK iOS về thư mục sdks của Theos
    - name: Setup iOS SDK
      run: |
        git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks

    # 3. Tiến hành compile bằng Xcode Toolchain có sẵn trên macOS 14
    - name: Compile Tweak dylib
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        make package FINALPACKAGE=1
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BedrockNBT-LITE-Package
        path: packages/*.deb