name: Build BedrockNBT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies (Linux Cross-Compile)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential perl git curl libssl-dev make clang

    # 1. Tạo thư mục và kéo SDK về trước để chặn Theos tự tải
     Berk:
    - name: Prepare Theos and SDKs Directory
      run: |
        mkdir -p $HOME/theos/sdks
        git clone --depth=1 https://github.com/theos/sdks.git $HOME/theos/sdks

    # 2. Cài đặt Theos với cờ tắt tự động download SDK để tránh lỗi API GitHub
    - name: Set up Theos Environment
      run: |
        export THEOS_AUTO_DOWNLOAD_SDKS=0
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        
    - name: Compile Tweak dylib
      run: |
        export THEOS=$HOME/theos
        make package FINALPACKAGE=1
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BedrockNBT-LITE-Package
        path: packages/*.deb